### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by antarr** [channeladam/ChannelAdam.Soap#1]
How can I set a Header for Basic Auth

**Comment by channeladam** [comment]
Basic Auth is part of your HTTP Request header... nothing to do with this library. This library only builds the SOAP XML.

If you want to add any arbitrary header block, use .WithHeader.AddBlock and pass in an XElement.

var envelope = SoapBuilder.CreateSoap11Envelope().WithHeader.AddBlock(XContainer headerBlock)
