### ISSUE TITLE
Refactoring Logic to use ChannelAdam.Soap

### ISSUE THREAD

**Issue by antarr** [channeladam/ChannelAdam.Soap#2]
I'm looking to use ChannelAdam.Soap for currently implemented server code that is having performance problems. I'm not very familiar with Soap however and this is not my code can you help me to refactor it to use your library.

### Initialize Video Conference
        public static async Task<VidyoConference> InitializeVidyoConference( TPICalEntry calEntry)
        {
            VidyoConference conf = null;

            if (!string.IsNullOrEmpty(calEntry?.OtherInfo))
            {
                AppUtils.LogInfo($"==>> InitializeVidyoConference : request for patient: {calEntry.Title} id ={calEntry.Id}");

                //get the appointment obj
                var aptEntity = new EntityRepository<Appointment>(DBUtils.DBService);
                var appt = aptEntity.Retrieve(new Guid(calEntry.TPItemId));
                _httpClient = new HttpClient();
                try
                {
                    var tag = calEntry.Id.ToString("N").Substring(2, 6);
                    //create room name and extension
                    var info = JsonConvert.DeserializeObject<OtherInfo>(calEntry.OtherInfo);
                    var items = info.ProviderName.Split(' ');
                    var roomname = items[0] + tag;
                    var extension = GetRoomExtension();

                    //usingthe create room api from the userportal web services binding
                    var requestBody = DefineCreateRoomRequest(roomname, extension);
                    var userWsdlUrl = VidyoPortalBaseUrl + VidyoPortalUserService;
                    var byteArray = Encoding.UTF8.GetBytes(VidyoSysCreds); 
                 
                    _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(byteArray));

                    var response = await _httpClient.PostAsync(userWsdlUrl, new StringContent(requestBody, Encoding.UTF8, "text/xml"));
                    if (response.IsSuccessStatusCode)
                    {
                        using (var stream = await response.Content.ReadAsStreamAsync())
                        {
                            var xml = XElement.Load(stream);

                            conf = CreateVidyoConference(xml);
                            if (conf != null)
                            {
                                conf.Title = calEntry.Title;
                                conf.AppointmentId = calEntry.TPItemId;
                                conf.CalEntryId = calEntry.Id.ToString();
                                conf.DateAndTime = calEntry.DateAndTime;
                                conf.StartTime = calEntry.StartTime;
                                conf.EndTime = calEntry.EndTime;
                                conf.Status = calEntry.Status;
                                if (appt != null)
                                {
                                    conf.CreatedAt = appt.CreatedAt;
                                    conf.CreatedBy = appt.CreatedBy;
                                }
                                conf.EventStatus = AppointmentStatus.Scheduled.Value;

                                var confEntity = new EntityRepository<VidyoConference>(DBUtils.DBService);
                                confEntity.Create(conf);
                                using (var repository = new VidyoRepository())
                                {
                                    repository.ConnectVidyoConference(new Guid(calEntry.TPItemId), conf.Id, new Guid(info.PatientId));
                                }
                            }
                            else
                                AppUtils.LogInfo($"== InitializeVidyoConference: CreateVidyoConference returned null : {response.ReasonPhrase}");
                        }
                    }
                    else
                    {
                      AppUtils.LogInfo("== InitializeVidyoConference Error: " + response.ReasonPhrase);
                    }
                }
            return conf;
        }

### Define Create Request Body
        private static string DefineCreateRoomRequest(string roomName, string extension)
        {
            var soapenv = SoapEnv;
            var v1 = NSUserPortal;

            var roomreqXml = new XDocument(
                new XDeclaration("1.0", "utf-8", string.Empty),
                new XElement(soapenv + "Envelope",
                    new XAttribute(XNamespace.Xmlns + "SOAP-ENV", soapenv),
                    new XAttribute(XNamespace.Xmlns + "v1", v1),
                    new XElement(soapenv + "Header"),
                    new XElement(soapenv + "Body",
                        new XElement(v1 + "CreateRoomRequest",
                            new XElement(v1 + "name", roomName),
                            new XElement(v1 + "extension", extension)))));
            var req = roomreqXml.ToString();
            return req;
        }

**Comment by channeladam** [comment]
This library will only provide an alternative to how you are creating roomreqXml in DefineCreateRoomRequest() - so you don't need to have the magic strings and constants for the envelope.

That code is fairly lean - you are unlikely to get a performance improvement by switching to this library.

Documentation: https://devzone.channeladam.com/library/channeladam-soap/
