### ISSUE TITLE
Guidance

### ISSUE THREAD

**Issue by antarr** [channeladam/ChannelAdam.Soap#3]
How would I create the following envelope?

```
<?xml version='1.0' encoding='UTF-8'?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v="http://portal.vidyo.com/user/v1_1">
    <soapenv:Body>
        <v:CreateRoomRequest>
            <v:name>roomOne4</v:name>
            <v:extension>262644233</v:extension>
        </v:CreateRoomRequest>
    </soapenv:Body>
</soapenv:Envelope>
```

**Comment by channeladam** [comment]
Please read the doco: https://devzone.channeladam.com/library/channeladam-soap/ 
and look at the Behaviour Specification code for examples: https://github.com/channeladam/ChannelAdam.Soap/blob/master/src/BehaviourSpecs/MakingSoap11UnitSteps.cs - especially from line 259

and https://github.com/channeladam/ChannelAdam.Soap/blob/master/src/BehaviourSpecs/TestData/XmlObjectWithRootAttribute.cs
