### ISSUE TITLE
Overloads for WithHeader.AddBlock()

### ISSUE THREAD

**Issue by asherber** [channeladam/ChannelAdam.Soap#4]
Very handy little library!

Is there a reason that `WithBody.AddEntry()` has overloads for raw XML and POCOs, but `WithHeader.AddBlock()` does not? I'd be happy to work on a PR for this.

**Comment by channeladam** [comment]
Thanks!
No reason. 
Good suggestion - working on it.

**Comment by channeladam** [comment]
Done. Grab the latest!

**Comment by channeladam** [comment]
Done. Grab the latest!

**Comment by asherber** [comment]
Thanks!
