### ISSUE TITLE
Suggestion for docs

### ISSUE THREAD

**Issue by asherber** [channeladam/ChannelAdam.Soap#5]
It might be helpful to point out in the docs that since `Build()` produces an `XContainer`, you can do all kinds of LINQish things with it. You can also pass in `SaveOptions.DisableFormatting` to `ToString()` to get unformatted XML.

(I was going to make unformatted XML a feature request until I examined the chained methods. In certain circumstances, all the carriage returns and spaces can really bloat a payload.)

**Comment by channeladam** [comment]
Done! Thanks.
