### ISSUE TITLE
Need Sample Project

### ISSUE THREAD

**Issue by x0d3r** [channeladam/ChannelAdam.Soap#7]
Would it be possible to add a sample project ?

**Comment by channeladam** [comment]
Have a look at the Behaviour Specification files:
- https://github.com/channeladam/ChannelAdam.Soap/blob/master/src/BehaviourSpecs/MakingSoap12.feature
- https://github.com/channeladam/ChannelAdam.Soap/blob/master/src/BehaviourSpecs/MakingSoap12UnitSteps.cs
- and similar files for Soap 1.1

They contains the unit tests where you can see how to use it - above and beyond the doco (https://devzone.channeladam.com/library/channeladam-soap/)
